<project xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>geo.marcos</groupId>
    <artifactId>Ejb3Chp7</artifactId>
    <version>v0</version>
  </parent>
  <artifactId>integ-war</artifactId>
  <packaging>war</packaging>
  <dependencies>
    <dependency>
      <groupId>geo.marcos</groupId>
      <artifactId>integ-ejb</artifactId>
      <version>v0</version>
  </dependency>
  <dependency>
    <groupId>javax</groupId>
    <artifactId>javaee-api</artifactId>
    <version>8.0</version>
    <scope>provided</scope>
  </dependency>
  <dependency>
    <groupId>javax.persistence</groupId>
    <artifactId>javax.persistence-api</artifactId>
    <version>2.2</version>
    <scope>provided</scope>
  </dependency>
  <dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>eclipselink</artifactId>
    <version>2.7.12</version>
  </dependency>
</dependencies>
</project>